### ISSUE TITLE
Add config value for custom user agent string in jhttp

### ISSUE THREAD

**Issue by Lukasz032** [creachadair/jrpc2#112]
When using a HTTP transport, requests have a certain `User-Agent` header. It's beneficial to set this to the application-related one.

A config value would be an ideal place for this, instead of hooking custom request interceptors in-between the normal request flow just for this task.

**Comment by creachadair** [comment]
I'm not convinced an additional option for this narrow use is worth adding to the library. There's already a channel option to override the client. It's only a few lines of code to shim that, something like:

```go
// UAClient is a shim for http.DefaultClient that overrides the User-Agent.
type UAClient string

func (u UAClient) Do(req *http.Request) (*http.Response, error) {
	req.Header.Set("User-Agent", string(u))
	return http.DefaultClient.Do(req)
}
```

and then plug that in. Here is [an example in the Go playground](https://go.dev/play/p/zkK6xCtS7ZH) that demonstrates it.

There are lots of policy headers a client _might_ want to set. In general, the `jhttp` package is meant to push JSON-RPC over HTTP as a transport, but an application that cares about other details of HTTP semantics might be better served by using HTTP directly instead of JSON-RPC.

**Comment by creachadair** [comment]
My example works as long as you wanted the default client anyway, which will often be the case. If you do want to wrap another client, though, it's not that much worse:

```go
// warning: untested
type UAClient struct{
  userAgent string
  client    jhttp.HTTPClient
}

func (u UAClient) Do(req *http.Request) (*http.Response, error) {
   req.Header.Set("User-Agent", u.userAgent)
   return u.client.Do(req)
}
```

or words to that effect. (This is why `jhttp` defines the client in terms of a restricted interface, since that's the only part it needs from the concrete type).
