### ISSUE TITLE
Support for UDP transport

### ISSUE THREAD

**Issue by okhowang** [creachadair/jrpc2#85]

**Comment by creachadair** [comment]
Hi @okhowang, can you say more about what you're looking for here?

Mechanically it's pretty straightforward to send and receive blobs via (say) a [UDPConn](https://pkg.go.dev/net#UDPConn), but it's unclear how to route requests and responses without a connection.  A `UDPConn` can be "connected" to establish a default address, but packets can originate from anywhere.

Because there are various ways to answer that question, this seems to me like a feature that should be implemented by the user of this module, rather than by the module itself. Am I missing some other subtlety that would make that difficult?

**Comment by okhowang** [comment]
> it's unclear how to route requests and responses without a connection

exactly. I work with a udp-based json-rpc protocol.

in client, I can use `net.DialUDP` to get a `UDPConn`, and wrap it as `Channel`.
but a think it could be bundle into library?

in server, I found `server.Loop` need an `Acceptor`, maybe we can make a virtual `Conn` once recieve udp package.
but it is hard to define when to close this `Conn`.
and how demuxing mutiple virtual `Conn ` on one `UDPConn` is also a problem

**Comment by creachadair** [comment]
> in client, I can use `net.DialUDP` to get a `UDPConn`, and wrap it as `Channel`. but a think it could be bundle into library?

Yes, certainly you could make a library of that. That's why `Channel` is defined as an interface, so that you can supply your own implementation of it.

> in server, I found `server.Loop` need an `Acceptor`, maybe we can make a virtual `Conn` once recieve udp package. but it is hard to define when to close this `Conn`. and how demuxing mutiple virtual `Conn ` on one `UDPConn` is also a problem

The `Close` method may not need to do anything special in the case of UDP—it would be fine to implement it as a no-op, e.g., `func (udpChannel) Close() error { return nil }` or similar. The interface requires that it be defined (since other channel types _do_ need an opportunity to close), but it doesn't have to do anything if there's nothing to do.

It seems to me that the interesting question is how to route messages properly. Maybe keeping a lookup table between request IDs and `net.Addr` would help—but even then, you have the trouble that different clients lack a clear way to tell which request IDs are "available". The JSON-RPC protocol isn't really well-suited to connectionless transports for this reason.

**Comment by creachadair** [comment]
Another possible option that occurred to me (but I haven't tested) might be:

```go
type udpChannel struct {
  *net.UDPConn
}

func (u udpChannel) Send(data []byte) error {
  _, err := u.Write(data)
  return err
}

func (u udpChannel) Recv() ([]byte, error) {
  var buf [1<<16]byte
  n, _, err := u.ReadFrom(buf[:])
  return buf[:n], err
}

type udpAccepter struct {
  addr *net.UDPAddr
}

func (u udpAccepter) Accept(_ context.Context) (channel.Channel, error) {
   conn, err := net.ListnUDP("udp", u.addr)
   if err != nil {
      return nil, err
   }
   return udpChannel{conn}, nil
}
```

That would essentially treat each ip/port pair from a client as a distinct "channel" and should, I suspect, route messages reasonably consistently. It's worth trying it out anyway.

**Comment by creachadair** [comment]
Actually upon further reflection, that won't quite do the trick, since the conn returned by ListenUDP does not expose a remote address for replies. DialUDP seems to populate that (as expected) but listen doesn't.
